### ISSUE TITLE
Distributing keys to other jails

### ISSUE THREAD

**Issue by nerdbeard** [JoergFiedler/freebsd-jailed-nginx#16]
Hi, Joerg.  Thanks so much for all the work you've shared.  Your ``freebsd-jail*`` infrastructure and the sysadmin experience it expresses have been a tremendous benefit to me.

I am working on a pair of roles which deploy jails, one hosting authoritative DNS and the other SMTP and IMAP services for a domain.    I hope to share them before June when I need to go live.

Each of these roles require signed keys that I am obtaining using your excellent ``freebsd-jailed-nginx``.  I am simply using a cron job on the jail host to periodically distribute keys from ``/iocage/jails/web/root/usr/local/etc/ssl/DOMAIN/`` to the equivalent folder on other jails.  This is ... okay, but not ideal.

I wonder how you would go about communicating events (like "key updated") from the web jail to the jail host in a simple and elegant way?  Or if you might have a better way of distributing the keys to other jails?

Thanks for your thoughts.

**Comment by JoergFiedler** [comment]
Hi @nerdbeard  …

thanks, I am happy that the roles are of same help to you. 

The problem you describe is one I tried to solve some time ago. Many ideas came to my mind, but tdue to lack of time I did not implement them so far. My main goal was always to keep the jails independen from each other. The script `acme.sh` I am using here supports some more modes to obtain the certificates. The most promising one was the `DNSmode`, but I hesitated to give the jail API access. That is why I dropped it.

Like you I also thought about having a script on the host that copies the files between jails. It should not be complicated to set up. Another idea was to mount the folders `…/ssl/DOMAIN` between the jails  - even simpler. Might just be an entry within the fstab for the jail. The bit more interesting problem is to trigger the reload when the files change. But also for this problem tools exists. In the end, due to lack of time, I just made my STMP,IMAP,… roles dependend on the nginx role and provide a basic NGINX config just for the purpose of updating the certificates on regualr basis. Restarting the services was then for free on the cost of exposing another service.

BTW, I am curious about the roles you will share because I also have some unpublished roles for postfix,cyrus,openldap. Maybe we can share some knowledge?

**Comment by nerdbeard** [comment]
Historically, there have not been good ways to mount the same filesystem at multiple mountpoints on FreeBSD.  Has this situation improved, perhaps thanks to ZFS?  Or maybe you are proposing to use NFS mounts via loopback?

I haven't gotten around to notifying services when the keys change, but it shouldn't be hard to notice when the copy destination differs from the source.

I guess I will push on with this strategy.  I need something simple that works for now, I can revisit it later.

I will let you know when I have published something.  The DNS role is based on nsd and the mail role is based on [this](https://poolp.org/posts/2019-09-14/setting-up-a-mail-server-with-opensmtpd-dovecot-and-rspamd/).  I also have a role for a peertube instance and it's already live but has issues I need to address.  I am interested in publishing everything I am using in hopes of suckering other people into doing my IT for me.

**Comment by JoergFiedler** [comment]
ok, just as an idea … this is how I use `nginx` role on my postfix role … following lines are from `meta/main.yml`

```
dependencies:
  - role: JoergFiedler.freebsd-jailed-nginx
    vars:
      nginx_pf_redirect: yes
      nginx_letsencrypt_enabled: yes
      nginx_letsencrypt_deploy_restart_services: 'nginx postfix'
      nginx_syslogd_server: '{{ jail_net_ip }}'
      nginx_tarsnap_enabled: no
      nginx_worker_processes: 1
      nginx_client_max_body_size: 64k
      nginx_servers:
        - aliases: '{{ postfix_certificate_aliases }}'
          force_https: yes
          force_www: no
          https:
            enabled: yes
            letsencrypt_enabled: yes
            key_file: '{{ postfix_key_file }}'
            certbundle_file: '{{ postfix_certbundle_file }}'
            dhparam_file: '{{ postfix_dhparam_file }}'
          name: '{{ postfix_mail_server_fqdn }}'
```
